### ISSUE TITLE
Permissions issue when running setup.sh

### ISSUE THREAD

**Issue by patrick-stephens** [jnsgruk/dotfiles#1]
Looks like it failed to install the terminator packages due to some issue acquiring the package lock: this was when run as normal user but with the correct password to elevate (other packages were fine). Re-ran as root (still required the BECOMES password for some reason) and seems to have got past it now.

**Comment by patrick-stephens** [comment]
Meant to include the fact it just closed the terminal when it errored out, had to check the logs to see why.
This was using the net-provision.sh approach, re-ran directly using setup.sh

**Comment by jnsgruk** [comment]
Fixed in https://github.com/jnsgruk/dotfiles/commit/4ed9e48635f4b4fd55caa33098f9305ee04c88fd
